library("fields") 
rm(list = ls())

d = function(x, y) {
  sqrt(sum((x - y)^2))
}

n = function(x, y) {
  # From x ---> y
  (y-x)/d(x,y)
}

n_particles = function(particles) {
  nb_part = nrow(particles)
  out = array(NA, dim = c(nb_part, nb_part, ncol(particles)))
  for(i in 1:nb_part) {
    for(j in 1:nb_part) {
      out[i,j,] = n(particles[i,], particles[j,])
    }
  }
  return(out)
}

f = function(dxy) {
  pmax(- abs(1 - dxy) + 1, 0)
}
# todo: let integral integral as 1 (over the current number of dimensions dim)
# x = seq(-4,4,length.out = 1000); plot(x, f(x))

grad_i = function(i, N, fD) {
  nb_part = dim(N)[1]
  nb_dim = dim(N)[3]
  idx_p_others = (1:nb_part)[-i]
  
  out = rep(0, nb_dim)
  for(j in idx_p_others) {
    out = out + N[i,j,] * fD[i,j]
  }
  out = out / nb_part
  return(out)
}

grad_fn = function(N, fD) {
  nb_part = dim(N)[1]
  nb_dim = dim(N)[3]
  out = matrix(NA, nrow = nb_part, ncol = nb_dim)
  for(i in 1:nb_part) {
    out[i,] = grad_i(i, N, fD)
  }
  return(out)
}

move = function(particles, types, eps = 0.1) {
  D = rdist(particles) # https://stackoverflow.com/questions/9879608
  fD = structure(vapply(D, f, numeric(1)), dim=dim(D)) # https://stackoverflow.com/questions/8579257
  N = n_particles(particles)
  grad = grad_fn(N, fD) 
  types_v = replicate(ncol(particles), types)
  particles = particles + eps * types_v * grad
  return(particles)
}

# points = matrix(runif(1000*100), nrow=1000, ncol=100)
particles = matrix(c(0,0,
                     1,0,
                     2,0), nrow=3, ncol=2, byrow = TRUE)
set.seed(1234)
particles = matrix(runif(100*2, -3, 3), nrow = 100, ncol = 2)
types = sign(runif(nrow(particles), -1, 1))

particles = matrix(c(0,0,
                     0.5,0.5,
                     0,10.5,
                     0.5,10), nrow = 4, ncol = 2, byrow = TRUE)
types = c(1, -1, 1, -1)

particles = matrix(c(0,0,
                     0.5,0,
                     0,0.5,
                     0.5,0.5), nrow = 4, ncol = 2, byrow = TRUE)
types = c(1, -1, 1, -1)


eps = 0.4

# particles = move(particles, types, eps); print(particles); plot(particles)

# points = matrix(runif(1000*100), nrow=1000, ncol=100)
particles = matrix(c(0,0,
                     1,0,
                     2,0), nrow=3, ncol=2, byrow = TRUE)
set.seed(1234)
particles = matrix(runif(100*2, -3, 3), nrow = 100, ncol = 2)
types = sign(runif(nrow(particles), -1, 1))

particles = matrix(c(0,0,
                     0.5,0.5,
                     0,10.5,
                     0.5,10), nrow = 4, ncol = 2, byrow = TRUE)
types = c(1, -1, 1, -1)

particles = matrix(c(0,0,
                     0.5,0,
                     0,0.5,
                     0.5,0.5), nrow = 4, ncol = 2, byrow = TRUE)
types = c(1, -1, 1, -1)


eps = 0.4

# particles = move(particles, types, eps); print(particles); plot(particles)
particles = move(particles, types, eps)#; plot(particles)
library("fields") 
rm(list = ls())

d = function(x, y) {
  sqrt(sum((x - y)^2))
}

n = function(x, y) {
  # From x ---> y
  (y-x)/d(x,y)
}

n_particles = function(particles) {
  nb_part = nrow(particles)
  out = array(NA, dim = c(nb_part, nb_part, ncol(particles)))
  for(i in 1:nb_part) {
    for(j in 1:nb_part) {
      out[i,j,] = n(particles[i,], particles[j,])
    }
  }
  return(out)
}

f = function(dxy) {
  pmax(- abs(1 - dxy) + 1, 0)
}
# todo: let integral integral as 1 (over the current number of dimensions dim)
# x = seq(-4,4,length.out = 1000); plot(x, f(x))

grad_i = function(i, N, fD) {
  nb_part = dim(N)[1]
  nb_dim = dim(N)[3]
  idx_p_others = (1:nb_part)[-i]
  
  out = rep(0, nb_dim)
  for(j in idx_p_others) {
    out = out + N[i,j,] * fD[i,j]
  }
  out = out / nb_part
  return(out)
}

grad_fn = function(N, fD) {
  nb_part = dim(N)[1]
  nb_dim = dim(N)[3]
  out = matrix(NA, nrow = nb_part, ncol = nb_dim)
  for(i in 1:nb_part) {
    out[i,] = grad_i(i, N, fD)
  }
  return(out)
}

move = function(particles, types, eps = 0.1) {
  D = rdist(particles) # https://stackoverflow.com/questions/9879608
  fD = structure(vapply(D, f, numeric(1)), dim=dim(D)) # https://stackoverflow.com/questions/8579257
  N = n_particles(particles)
  grad = grad_fn(N, fD) 
  types_v = replicate(ncol(particles), types)
  particles = particles + eps * types_v * grad
  return(particles)
}

# points = matrix(runif(1000*100), nrow=1000, ncol=100)
particles = matrix(c(0,0,
                     1,0,
                     2,0), nrow=3, ncol=2, byrow = TRUE)
set.seed(1234)
particles = matrix(runif(100*2, -3, 3), nrow = 100, ncol = 2)
types = sign(runif(nrow(particles), -1, 1))

# particles = matrix(c(0,0,
#                      0.5,0.5,
#                      0,10.5,
#                      0.5,10), nrow = 4, ncol = 2, byrow = TRUE)
ecart = 1.8121475245 # default = 1.9 / 2 = no effect / 
# <= 1.8121475244 = inner too much so blocked
# >= 1.8121475245 = ok change direction
particles = matrix(c(0  ,   0,
                     0.5,   0,
                     0  , ecart,
                     0.5, ecart), nrow = 4, ncol = 2, byrow = TRUE)
types = c(1, -1, 1, -1)

# particles = matrix(c(0,   0,
#                      0.5, 0,
#                      0,   1,
#                      0.5, 1), nrow = 4, ncol = 2, byrow = TRUE)
# types = c(1, -1, 1, -1)


eps = 0.4

# particles = move(particles, types, eps); print(particles); plot(particles)
plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)
particles = move(particles, types, eps); plot(particles, asp = 1)


